/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;

/**
 *
 * @author jonaranjo
 */
public class EstadisticasWindow extends javax.swing.JFrame {
    
    private Controlador controlador;
    /**
     * Constructor
     */
    public EstadisticasWindow() {
        controlador = new Controlador();
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void setControlador(Controlador pControlador)
    {
        this.controlador = pControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReporte = new javax.swing.JTextArea();
        bntReporte = new javax.swing.JButton();
        bntEscuela_mayorGasto = new javax.swing.JButton();
        bntEmp_MayorCopias = new javax.swing.JButton();
        bntPorcCopiasDocente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtAreaReporte.setColumns(20);
        txtAreaReporte.setRows(5);
        jScrollPane1.setViewportView(txtAreaReporte);

        bntReporte.setText("Generar Reporte");
        bntReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntReporteActionPerformed(evt);
            }
        });

        bntEscuela_mayorGasto.setText("Escuela con mayor gasto de papel");
        bntEscuela_mayorGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEscuela_mayorGastoActionPerformed(evt);
            }
        });

        bntEmp_MayorCopias.setText("Empleado con más copias");
        bntEmp_MayorCopias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEmp_MayorCopiasActionPerformed(evt);
            }
        });

        bntPorcCopiasDocente.setText("Porcentajes de copias docentes");
        bntPorcCopiasDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPorcCopiasDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(bntReporte))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntPorcCopiasDocente)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bntEscuela_mayorGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntEmp_MayorCopias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bntReporte)
                        .addGap(70, 70, 70)
                        .addComponent(bntEscuela_mayorGasto)
                        .addGap(55, 55, 55)
                        .addComponent(bntEmp_MayorCopias)
                        .addGap(63, 63, 63)
                        .addComponent(bntPorcCopiasDocente)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntReporteActionPerformed
        String reporte = this.controlador.generarReporte();
        txtAreaReporte.setText(reporte);
    }//GEN-LAST:event_bntReporteActionPerformed

    private void bntEscuela_mayorGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEscuela_mayorGastoActionPerformed
        txtAreaReporte.setText("");
        txtAreaReporte.setText(this.controlador.getEscuelaMasGastoPapel());
    }//GEN-LAST:event_bntEscuela_mayorGastoActionPerformed

    private void bntEmp_MayorCopiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEmp_MayorCopiasActionPerformed
        txtAreaReporte.setText("");
        txtAreaReporte.setText(this.controlador.getEmpMasCopias());
    }//GEN-LAST:event_bntEmp_MayorCopiasActionPerformed

    private void bntPorcCopiasDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPorcCopiasDocenteActionPerformed
        txtAreaReporte.setText("");
        txtAreaReporte.setText(this.controlador.getPorceCopiasDocentes());
    }//GEN-LAST:event_bntPorcCopiasDocenteActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEmp_MayorCopias;
    private javax.swing.JButton bntEscuela_mayorGasto;
    private javax.swing.JButton bntPorcCopiasDocente;
    private javax.swing.JButton bntReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaReporte;
    // End of variables declaration//GEN-END:variables
}
